steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/tough-bearing-364504/nextjs-cloudrun-app', '.']

#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['run', 'deploy', 'nextjs-cloudrun-app', '--image', 'gcr.io/tough-bearing-364504/nextjs-cloudrun-app', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']